SELECT 
	 tdl.TX_ID
	,POST_DATE
	,PERIOD
	,MODIFIER_ONE
	,MODIFIER_TWO
	,MODIFIER_THREE
	,MODIFIER_FOUR
	,TYPE_OF_SERVICE
	,DETAIL_TYPE
	,SERV_AREA_ID
	,ats.TX_ID
	,BC_HX_INVOICE_NUM
FROM
	CLARITY_TDL_TRAN tdl
	LEFT JOIN ARPB_TX_STMCLAIMHX ats on tdl.tx_id = ats.tx_id
WHERE 
	TYPE_OF_SERVICE = '7'
	and
	DETAIL_TYPE in ('1','10')
	and POST_DATE between '06/01/2014' and '06/30/2014'