/*
I need a report that I think there’s potential for the cube to be able to do it but I can’t figure out how…

I need to look at specific payor plans (1006005, 3124001, 3124004, 3124006, 3124007, 3124008) and the total amount that is left due. Fields to include (basically my column headings): 
Patient name, DOB, Subscriber Number, Subscriber name, relationship, Invoice number, Provider, DOS, Place of Service, Billed Amount, Outstanding amount, Plan ID, Plan Name
700 170K

mrn 10/23/15 11/10/2015 $106 E2808075 Kimberly Miller

I also want to look at the same plans but look at payments that have been made in the last couple months. Same column headings.
6 months

just payments

RPB102 - PB RWB

7/10/15 103, 163, E2855675
o
*/

select 
 ARPB_TRANSACTIONS.TX_ID
,PATIENT.PAT_NAME
,PATIENT.BIRTH_DATE
,COVERAGE.SUBSCR_NUM
,COVERAGE.SUBSCR_NAME
,'' as RELATIONSHIP
,'' as INVOICE
,ARPB_TRANSACTIONS.BILLING_PROV_ID
,CLARITY_SER_BILL.PROV_NAME
,ARPB_TRANSACTIONS.SERV_PROVIDER_ID
,CLARITY_SER_PERF.PROV_NAME
,ARPB_TRANSACTIONS.SERVICE_DATE
,CLARITY_POS.POS_NAME
,ARPB_TRANSACTIONS.AMOUNT
,ARPB_TRANSACTIONS.OUTSTANDING_AMT
,CLARITY_EPP.BENEFIT_PLAN_ID
,CLARITY_EPP.BENEFIT_PLAN_NAME
,ARPB_TRANSACTIONS.SERVICE_AREA_ID

from 

ARPB_TRANSACTIONS
left join ARPB_TX_MODERATE on ARPB_TRANSACTIONS.TX_ID = ARPB_TX_MODERATE.TX_ID
left join PATIENT on ARPB_TRANSACTIONS.PATIENT_ID = PATIENT.PAT_ID
left join CLARITY_EPP on ARPB_TX_MODERATE.COVERAGE_PLAN_ID = CLARITY_EPP.BENEFIT_PLAN_ID
left join CLARITY_SER CLARITY_SER_BILL on ARPB_TRANSACTIONS.BILLING_PROV_ID = CLARITY_SER_BILL.PROV_ID
left join CLARITY_SER CLARITY_SER_PERF on ARPB_TRANSACTIONS.SERV_PROVIDER_ID = CLARITY_SER_PERF.PROV_ID
left join COVERAGE on ARPB_TRANSACTIONS.COVERAGE_ID = COVERAGE.COVERAGE_ID
left join CLARITY_POS on ARPB_TRANSACTIONS.POS_ID = CLARITY_POS.POS_ID

where

CLARITY_EPP.BENEFIT_PLAN_ID in (1006005, 3124001, 3124004, 3124006, 3124007, 3124008) -- HIGHMARK BENEFIT PLANS
--and PATIENT.PAT_ID = 'Z2856399' -- PHILIPS, BERNARD
and ARPB_TRANSACTIONS.TX_TYPE_C = 1
and ARPB_TRANSACTIONS.OUTSTANDING_AMT <> 0
and ARPB_TRANSACTIONS.SERVICE_AREA_ID in (11,13,16,17,18,19,21,1312)

order by PAT_NAME, SERVICE_DATE
