SELECT EDG.DX_NAME "DIAGNOSIS NAME"
       ,CASE EDG.RECORD_TYPE_C
             WHEN '1'
                    THEN 'TERM'
             WHEN '2'
                    THEN 'CODE'
             WHEN '3'
                    THEN 'BOTH CODE AND TERM'
             END "RECORD TYPE"
       ,EDG.REF_BILL_CODE "ICD CODE"
       ,EDG.REF_BILL_CODE_SET_C "ICD VERSION CODE"
       ,ZEDGC.NAME "ICD VERSION NAME"
FROM CLARITY_EDG EDG
LEFT OUTER JOIN ZC_EDG_CODE_SET ZEDGC ON ZEDGC.EDG_CODE_SET_C = EDG.REF_BILL_CODE_SET_C
--Record Type of "CODE" which excludes TERM and BOTH CODE AND TERM
WHERE EDG.RECORD_TYPE_C IN (2)
ORDER BY DX_NAME;