SELECT MONTHS.MONTH_END_DT, MYC_MESG.SUBJECT, PAT_ENC.ENC_CLOSE_TIME, PAT_ENC.PAT_ID, PAT_ENC.CONTACT_DATE, TRANSACTIONS.ACCOUNT_ID,
COALESCE(MYC_MESG.CREATED_TIME,PAT_ENC.ENC_INSTANT) CREATED_TIME,
COALESCE(TRANSACTIONS.TOTAL_MATCH_AMT,0) TOTAL_MATCH_AMT,
COALESCE(TRANSACTIONS.TOTAL_MTCH_INS_AMT,0) TOTAL_MTCH_INS_AMT,
CLARITY_SER.PROV_NAME BILLING_PROVIDER, CLARITY_SER_2.PROV_NAME SERVICE_PROVIDER, TRANSACTIONS.BILLING_PROV_ID, TRANSACTIONS.SERV_PROVIDER_ID,
CLARITY_EAP.SHORT_NAME PROC_NAME, CLARITY_EPM.PAYOR_NAME, CLARITY_DEP.DEPARTMENT_NAME, TRANSACTIONS.SERVICE_AREA_ID, zc10.name SERV_AREA_NAME,
PATIENT.PAT_NAME, PATIENT.PAT_MRN_ID, PATIENT.BIRTH_DATE, PATIENT.ZIP, ZC_SEX.NAME ZC_SEX_NAME, ZC_ETHNIC_GROUP.NAME ETHNIC_GROUP
FROM clarity.dbo.PAT_ENC
INNER JOIN clarity.dbo.V_MONTHSBACK
ON V_MONTHSBACK.MONTHS_BACK < 12 AND PAT_ENC.CONTACT_DATE between V_MONTHSBACK.MONTH_BEGIN_DT and V_MONTHSBACK.MONTH_END_DT


AND PAT_ENC.ENC_TYPE_C = '62' AND PAT_ENC.ENC_CLOSED_YN = 'Y'
and pat_enc.pat_id = 'Z388232'
--AND ((0 in {?Service Area}) or PAT_ENC.SERV_AREA_ID in {?Service Area})
--AND ((0 in {?Department}) or PAT_ENC.DEPARTMENT_ID in {?Department})
left JOIN 
(
	-- Select billing related information for each E-visit encounter
	SELECT NON_NULL_ENC_CSN.PAT_ENC_CSN_ID, NON_NULL_ENC_CSN.ACCOUNT_ID, NON_NULL_ENC_CSN.BILLING_PROV_ID,
		NON_NULL_ENC_CSN.SERV_PROVIDER_ID, NON_NULL_ENC_CSN.TOTAL_MATCH_AMT, NON_NULL_ENC_CSN.TOTAL_MTCH_INS_AMT, 
		COALESCE(NULL_ENC_CSN.PAYOR_ID,NON_NULL_ENC_CSN.PAYOR_ID) PAYOR_ID, NON_NULL_ENC_CSN.SERVICE_AREA_ID
	FROM (
		SELECT PAYOR_ID, TX_BATCH_NUM, ACCOUNT_ID, TOTAL_MTCH_INS_AMT, POST_DATE, PAT_ENC_CSN_ID, BILLING_PROV_ID, SERV_PROVIDER_ID, TOTAL_MATCH_AMT, ARPB_TRANSACTIONS.SERVICE_AREA_ID
		FROM clarity.dbo.ARPB_TRANSACTIONS
		WHERE PAT_ENC_CSN_ID IS NOT NULL AND TOTAL_MATCH_AMT < 0
	--	AND (('0' in {?Billing Provider}) or ARPB_TRANSACTIONS.BILLING_PROV_ID in {?Billing Provider})
	--	AND (('0' in {?Service Provider}) or ARPB_TRANSACTIONS.SERV_PROVIDER_ID in {?Service Provider})
	) NON_NULL_ENC_CSN
	LEFT JOIN (
		SELECT PAYOR_ID, TX_BATCH_NUM, ACCOUNT_ID, TOTAL_MTCH_INS_AMT, POST_DATE
		FROM clarity.dbo.ARPB_TRANSACTIONS
		WHERE PAT_ENC_CSN_ID IS NULL AND TOTAL_MTCH_INS_AMT > 0
	) NULL_ENC_CSN
	ON NON_NULL_ENC_CSN.TX_BATCH_NUM = NULL_ENC_CSN.TX_BATCH_NUM AND NON_NULL_ENC_CSN.ACCOUNT_ID = NULL_ENC_CSN.ACCOUNT_ID 
		AND NON_NULL_ENC_CSN.TOTAL_MTCH_INS_AMT = -1 * NULL_ENC_CSN.TOTAL_MTCH_INS_AMT AND NON_NULL_ENC_CSN.POST_DATE = NULL_ENC_CSN.POST_DATE
) TRANSACTIONS
ON TRANSACTIONS.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID AND TRANSACTIONS.TOTAL_MATCH_AMT < 0
LEFT JOIN clarity.dbo.CLARITY_DEP
ON CLARITY_DEP.DEPARTMENT_ID = PAT_ENC.DEPARTMENT_ID
LEFT JOIN clarity.dbo.CLARITY_SER
ON CLARITY_SER.PROV_ID = TRANSACTIONS.BILLING_PROV_ID
LEFT JOIN clarity.dbo.CLARITY_SER CLARITY_SER_2
ON CLARITY_SER_2.PROV_ID = TRANSACTIONS.SERV_PROVIDER_ID
LEFT JOIN clarity.dbo.CLARITY_EAP
ON CLARITY_EAP.PROC_ID = PAT_ENC.LOS_PRIME_PROC_ID
LEFT JOIN clarity.dbo.CLARITY_EPM
ON CLARITY_EPM.PAYOR_ID = TRANSACTIONS.PAYOR_ID
LEFT JOIN clarity.dbo.zc_loc_rpt_grp_10 zc10
ON zc10.rpt_grp_ten  = TRANSACTIONS.SERVICE_AREA_ID
LEFT JOIN clarity.dbo.PATIENT
ON PATIENT.PAT_ID = PAT_ENC.PAT_ID
LEFT JOIN clarity.dbo.MYC_MESG
ON TRANSACTIONS.PAT_ENC_CSN_ID = MYC_MESG.PAT_ENC_CSN_ID AND MYC_MESG.MYC_MSG_TYP_C = 25
and myc_mesg.tofrom_pat_c = 2
LEFT JOIN clarity.dbo.ZC_SEX 
ON ZC_SEX.RCPT_MEM_SEX_C = PATIENT.SEX_C
LEFT JOIN clarity.dbo.ZC_ETHNIC_GROUP
ON ZC_ETHNIC_GROUP.ETHNIC_GROUP_C = PATIENT.ETHNIC_GROUP_C
RIGHT JOIN
(
	SELECT MONTH_END_DT, MONTH_BEGIN_DT
	FROM clarity.dbo.V_MONTHSBACK
	WHERE MONTHS_BACK < 12
) MONTHS
ON MONTHS.MONTH_END_DT = V_MONTHSBACK.MONTH_END_DT


