select distinct
 pat.PAT_ID as 'Patient ID'
,pat.PAT_MRN_ID as 'MRN'
,pat.PAT_FIRST_NAME as 'First Name'
,pat.PAT_MIDDLE_NAME as 'Middle Initial'
,pat.PAT_LAST_NAME as 'Last Name'
,convert(varchar(10), cast(pat.BIRTH_DATE as date), 101) as 'DOB'
,sex.ABBR as 'Gender'
,pat.SSN as 'SSN'
,pat.ADD_LINE_1 as 'Address 1'
,pat.ADD_LINE_1 as 'Address 2'
,pat.CITY as 'City'
,state.ABBR as 'State'
,pat.ZIP as 'Zip'
,zms.NAME as 'Marital Status'
,zes.NAME as 'Employee Status'
,'' as 'Chart No.'
,'' as 'Signature on File'
,coalesce(pat.HOME_PHONE, '000-000-0000') as 'Home Phone'
,coalesce(pat.WORK_PHONE, '000-000-0000') as 'Work Phone'
,'' as 'Cell Phone'
,pat.EMAIL_ADDRESS as 'Email'
,'' as 'Race'
,'' as 'Ethnicity'
,case when pac.FIN_CLASS = 4 then 0 else pac.PAYOR_ID end as 'HF Payer ID (P)'
,case when pac.FIN_CLASS = 4 then 'Self-Pay' else epm.PAYOR_NAME end as 'Insurance Type (P)'
,cov.GROUP_NAME as 'Group Name (P)'
,cov.GROUP_NUM as 'Group Number (P)'
,cov.SUBSCR_NUM as 'Insureds ID Number (P)'
,cov.ECD_TABLE_DEF_COPAY as 'Co-Pay (P)'
,'' as 'Insureds Accept Assignment (P)'
,'' as 'Patients Relationship (P)'
,cov.SUBSCR_NAME as 'Insureds First Name (P)'
,'' as 'Insureds Middle Initial (P)'
,'' as 'Insureds Last Name (P)'
,'' as 'Insureds DOB (P)'
,'' as 'Insureds Gender (P)'
,'' as 'Insureds Address 1 (P)'
,'' as 'Insureds Address 2 (P)'
,'' as 'Insureds City (P)'
,'' as 'Insureds State (P)'
,'' as 'Insureds Zip (P)'
,'' as 'Insureds Phone (P)'
,'' as 'Authorization No (P)'
,'' as 'Emergency First Name'
,'' as 'Emergency Last Name'
,'' as 'Emergency Phone'
,'' as 'Emergency Relation'
,'' as 'HF Payer ID (S)'
,'' as 'Insurance Type (S)'
,'' as 'Group Name (S)'
,'' as 'Group Number (S)'
,'' as 'Insureds ID Number (S)'
,'' as ' Co-Pay (S)'
,'' as ' Insureds Accept Assignment (S)'
,'' as ' Patients Relationship (S)'
,'' as 'Insureds First Name (S)'
,'' as 'Insureds Middle Initial (S)'
,'' as 'Insureds Last Name (S)'
,'' as 'Insureds DOB (S)'
,'' as 'Insureds Gender (S)'
,'' as 'Insureds Address 1 (S)'
,'' as 'Insureds Address 2 (S)'
,'' as 'Insureds City (S)'
,'' as 'Insureds State (S)'
,'' as 'Insureds Zip (S)'
,'' as 'Insureds Phone (S)'
,'' as 'Authorization No (S)'
,'' as 'HF Payer ID (T)'
,'' as 'Insurance Type (T)'
,'' as 'Group Name (T)'
,'' as 'Group Number (T)'
,'' as 'Insureds ID Number (T)'
,'' as 'Co-Pay (T)'
,'' as 'Insureds Accept Assignment (T)'
,'' as 'Patients Relationship (T)'
,'' as 'Insureds First Name (T)'
,'' as 'Insureds Middle Initial (T)'
,'' as 'Insureds Last Name (T)'
,'' as 'Insureds DOB (T)'
,'' as 'Insureds Gender (T)'
,'' as 'Insureds Address 1 (T)'
,'' as 'Insureds Address 2 (T)'
,'' as 'Insureds City (T)'
,'' as 'Insureds State (T)'
,'' as 'Insureds Zip (T)'
,'' as 'Insureds Phone (T)'
,'' as 'Authorization No (T)'
,rel.NAME as 'Guarantor Relation to Patient'
,acct.ACCOUNT_NAME as 'Guarantor First Name'
,'' as 'Guarantors Middle Initial'
,'' as 'Guarantor Last Name'
,'' as 'Guarantors DOB'
,'' as 'Guarantors Gender'
,'' as 'Guarantor Address 1'
,'' as 'Guarantor Address 2'
,'' as 'Guarantor City'
,'' as 'Guarantor State'
,'' as 'Guarantor Zip'
,'' as 'Guarantor Home Phone'
,'' as 'Guarantor Work Phone'
,'' as 'Guarantor SSN'
,'' as 'Guarantor Employer Name'
,'' as 'Guarantor Employer Address 1'
,'' as 'Guarantor Employer Address 2'
,'' as 'Guarantor Employer City'
,'' as 'Guarantor Employer State'
,'' as 'Guarantor Employer Zip'
,'' as 'Guarantor Account Number'
,'' as 'Language'
,'' as 'Referring Provider NPI'
,'' as 'Location External ID'

from PAT_ACCT_CVG pac
left join PATIENT pat on pat.PAT_ID = pac.PAT_ID
left join ZC_SEX sex on sex.RCPT_MEM_SEX_C = pat.SEX_C
left join ZC_STATE state on state.STATE_C = pat.STATE_C
left join ZC_MARITAL_STATUS zms on zms.MARITAL_STATUS_C = pat.MARITAL_STATUS_C
left join ZC_EMPY_STATUS zes on zes.EMPY_STATUS_C = pat.EMPY_STATUS_C
left join ACCOUNT acct on acct.ACCOUNT_ID = pac.ACCOUNT_ID
left join ZC_GUAR_REL_TO_PAT rel on rel.GUAR_REL_TO_PAT_C = pac.GUAR_PAT_REL
left join CLARITY_EPM epm on epm.PAYOR_ID = pac.PAYOR_ID
left join COVERAGE cov on cov.COVERAGE_ID = pac.COVERAGE_ID

where 
pac.ACCOUNT_TYPE_C  = 1
and pac.ACCOUNT_ACTIVE_YN = 'Y'
and pac.SERV_AREA_ID =1302


order by pat.PAT_ID