--declare @start_date as date = EPIC_UTIL.EFN_DIN('{?Start Date}')
--declare @end_date as date = EPIC_UTIL.EFN_DIN('{?End Date}')


declare @start_date as date = EPIC_UTIL.EFN_DIN('mb-2')
declare @end_date as date = EPIC_UTIL.EFN_DIN('me-2')
 
--select 

--sum(amount)

--from 
--(

SELECT "CLARITY_TDL_TRAN"."SERV_AREA_ID" as SERVICE_AREA_ID
	,"CLARITY_TDL_TRAN"."DETAIL_TYPE"
	,"CLARITY_TDL_TRAN"."POST_DATE"
	,"CLARITY_TDL_TRAN"."BILLING_PROVIDER_ID"
	,"CLARITY_SER_BILLING"."PROV_ID" as BILL_PROV_ID
	,"CLARITY_SER_BILLING"."PROV_NAME" as BILL_PROV_NAME
	,"CLARITY_TDL_TRAN"."DEPT_ID" as DEPARTMENT_ID
	,"CLARITY_DEP"."DEPARTMENT_ID" as DEPT_ID
	,"CLARITY_DEP"."DEPARTMENT_NAME" as DEPT_NAME
	,"CLARITY_DEP"."SPECIALTY"
	,"CLARITY_TDL_TRAN"."LOC_ID" as LOCATION_ID
	,"CLARITY_LOC"."LOC_ID" 
	,"CLARITY_LOC"."LOC_NAME"
	,"CLARITY_TDL_TRAN"."ORIGINAL_FIN_CLASS"
	,"ZC_FINANCIAL_CLASS"."FINANCIAL_CLASS"
	,"ZC_FINANCIAL_CLASS"."NAME" as FINANCIAL_CLASS_NAME
	,"CLARITY_TDL_TRAN"."AMOUNT"
	,"CLARITY_TDL_TRAN"."POS_ID" as PLACE_OF_SERVICE
	,"CLARITY_POS"."POS_ID"
	,"CLARITY_POS"."POS_NAME"
	,"CLARITY_POS"."POS_TYPE"
	,"CLARITY_SA"."SERV_AREA_ID"
	,"CLARITY_SA"."SERV_AREA_NAME"
	,"CLARITY_TDL_TRAN"."PERFORMING_PROV_ID"
	,"CLARITY_TDL_TRAN"."TX_ID"
	,"CLARITY_DEP"."GL_PREFIX" as dep_gl_prefix
	,"CLARITY_LOC"."GL_PREFIX" as loc_gl_prefix
FROM (
	(
		(
			(
				(
					"Clarity"."dbo"."CLARITY_TDL_TRAN" "CLARITY_TDL_TRAN" LEFT OUTER JOIN "Clarity"."dbo"."CLARITY_SA" "CLARITY_SA" ON "CLARITY_TDL_TRAN"."SERV_AREA_ID" = "CLARITY_SA"."SERV_AREA_ID"
					) LEFT OUTER JOIN "Clarity"."dbo"."CLARITY_LOC" "CLARITY_LOC" ON "CLARITY_TDL_TRAN"."LOC_ID" = "CLARITY_LOC"."LOC_ID"
				) LEFT OUTER JOIN "Clarity"."dbo"."CLARITY_DEP" "CLARITY_DEP" ON "CLARITY_TDL_TRAN"."DEPT_ID" = "CLARITY_DEP"."DEPARTMENT_ID"
			) LEFT OUTER JOIN "Clarity"."dbo"."CLARITY_POS" "CLARITY_POS" ON "CLARITY_TDL_TRAN"."POS_ID" = "CLARITY_POS"."POS_ID"
		) LEFT OUTER JOIN "Clarity"."dbo"."CLARITY_SER" "CLARITY_SER_BILLING" ON "CLARITY_TDL_TRAN"."BILLING_PROVIDER_ID" = "CLARITY_SER_BILLING"."PROV_ID"
	)
LEFT OUTER JOIN "Clarity"."dbo"."ZC_FINANCIAL_CLASS" "ZC_FINANCIAL_CLASS" ON "CLARITY_TDL_TRAN"."ORIGINAL_FIN_CLASS" = "ZC_FINANCIAL_CLASS"."FINANCIAL_CLASS"
WHERE "CLARITY_TDL_TRAN"."POST_DATE" >= @start_date
		AND "CLARITY_TDL_TRAN"."POST_DATE" <= @end_date

		
and clarity_tdl_tran.serv_area_id in (11,13,16,17,18,19)
		and detail_type in (2,5,11,20,22,32,33)
		--)a