select ser.prov_id, prov_name, dep.department_id, department_name
from clarity_ser ser
left join clarity_ser_dept csd on ser.prov_id = csd.prov_id
inner join clarity_dep dep on csd.department_id = dep.department_id
where prov_name like '%gavrila%'
or prov_name like '%see-yin%'
or prov_name like'%lawal%'
or prov_name like'%huckaby%'
or prov_name like'%coomer%'
or prov_name like'%zapiecki%'
or prov_name like'%peyton, joseph%'
or prov_name like'%burke, lisa%'
or prov_name like'%daiber%'
or prov_name like'%forche%'
or prov_name like'%rohrs, heather%'
or prov_name like'%smith, kelly%'
or prov_name like'%burgoon%'
or prov_name like'%theiss%'
or prov_name like'%patmon%'
or prov_name like'%ranker, chase%'
or prov_name like'%taddeo%'
or prov_name like'%calhoun%'
or prov_name like'%keeler%'
or prov_name like'%semma%'
or prov_name like'%david, brianna%'
or prov_name like'%kastel%'
or prov_name like'%waldman, margot%'
or prov_name like'%abdulrasool%'
or prov_name like'%devabhaktuni%'
or prov_name like'%hashmi, afreeda%'
or prov_name like'%kim, susie%'
or prov_name like'%leon, michael%'
or prov_name like'%flora, monica%'
or prov_name like'%bhatt, pranav%'
or prov_name like'%hodon%'
or prov_name like'%espinoza%'
or prov_name like'%retholtz%'
or prov_name like'%moriah%'
or prov_name like'%wilcox%'
order by prov_name asc
