
SELECT
DISTINCT V_IMG_STUDY.ORDER_ID AS 'ORDER ID'
,PATIENT.PAT_MRN_ID AS 'Patient ID'
,PATIENT.PAT_NAME AS 'Patient Name'
,V_IMG_STUDY.BEGIN_EXAM_DTTM as 'Begin Exam Date'
,V_IMG_STUDY.ACCESSION_NUM AS 'Accession Number'
,CLARITY_EAP.PROC_NAME AS 'Procedure Name'
,CLARITY_LOC.LOC_NAME AS 'Ordering Location'
,CLARITY_DEP.DEPARTMENT_NAME AS 'Ordering Department'
,CLARITY_SER_finalizing.PROV_NAME AS 'Finalizing Provider'
--,V_IMG_STUDY.STUDY_STATUS_C AS 'Study Status'
,ZC_RADIOLOGY_STS.name AS 'Study Status 2' --gets actual status name (final, end exam, etc)
,V_IMG_STUDY.IS_CANCELED_YN AS 'Is Canceled'
,V_IMG_STUDY.ORDERING_CSN_ID AS 'Ordering csn'  -- temporary
,V_IMG_STUDY.PERFORMING_CSN_ID AS 'Perf csn'    -- temporary
--,PAT_ENC_2_uncancelled.BILL_NUM AS 'ACCOUNT NUMBER uncancelled' --show this by default
--,PAT_ENC_2_cancelled.BILL_NUM AS 'acct num cancelled' -- pull this value in if the above is NULL.  Note that this is multiple response, so would 
, CASE WHEN PAT_ENC_2_uncancelled.BILL_NUM is NULL then PAT_ENC_2_cancelled.BILL_NUM else PAT_ENC_2_uncancelled.BILL_NUM END AS 'ACCOUNT NUMBER'  -- uncancelled and cancelled account numbers
   

FROM
V_IMG_STUDY
INNER JOIN PATIENT ON V_IMG_STUDY.PAT_ID = PATIENT.PAT_ID
INNER JOIN PATIENT_3 ON V_IMG_STUDY.PAT_ID = PATIENT_3.PAT_ID
LEFT OUTER JOIN ORDER_RAD_PRELIM ON V_IMG_STUDY.ORDER_ID = ORDER_RAD_PRELIM.ORDER_PROC_ID
LEFT OUTER JOIN CLARITY_SER CLARITY_SER_finalizing ON V_IMG_STUDY.FINALIZING_PROV_ID = CLARITY_SER_finalizing.PROV_ID
LEFT OUTER JOIN CLARITY_SER CLARITY_SER_prelim ON ORDER_RAD_PRELIM.PROV_ID = CLARITY_SER_prelim.PROV_ID  --link to preliming provider, but this is never used
LEFT OUTER JOIN ZC_RADIOLOGY_STS ON V_IMG_STUDY.STUDY_STATUS_C = ZC_RADIOLOGY_STS.RADIOLOGY_STATUS_C  --get study status int value
INNER JOIN CLARITY_EAP ON V_IMG_STUDY.PROC_ID = CLARITY_EAP.PROC_ID
INNER JOIN CLARITY_DEP ON V_IMG_STUDY.ORDERING_LOGIN_DEP_ID = CLARITY_DEP.DEPARTMENT_ID
INNER JOIN CLARITY_LOC ON CLARITY_DEP.REV_LOC_ID = CLARITY_LOC.LOC_ID
--LEFT OUTER JOIN ZC_PROCEDURE_TYPE ON CLARITY_EAP.TYPE_C = ZC_PROCEDURE_TYPE.PROC_TYPE  - shows name of procedure
LEFT OUTER JOIN PAT_ENC_2 PAT_ENC_2_uncancelled ON V_IMG_STUDY.PERFORMING_CSN_ID = PAT_ENC_2_uncancelled.PAT_ENC_CSN_ID -- link to performing encounter table, if available (uncancelled appts)
LEFT OUTER JOIN (Select ORDER_ID, MAX(LINE) as MaxLine, CANC_APPT_ASN FROM ORD_CANC_APPT_TRK GROUP BY ORDER_ID, CANC_APPT_ASN) ORD_CANC_APPT_TRK ON V_IMG_STUDY.ORDER_ID = ORD_CANC_APPT_TRK.ORDER_ID  -- LINK to cancelled appt table
left outer join PAT_ENC ON ORD_CANC_APPT_TRK.CANC_APPT_ASN = PAT_ENC.APPT_SERIAL_NO -- link to pt encounter
left outer join PAT_ENC_2 PAT_ENC_2_cancelled ON PAT_ENC.PAT_ENC_CSN_ID = PAT_ENC_2_cancelled.PAT_ENC_CSN_ID -- link to acct number

WHERE
PATIENT_3.IS_TEST_PAT_YN <> 'Y'
AND V_IMG_STUDY.BEGIN_EXAM_DTTM >= '2016-01-01'
AND V_IMG_STUDY.BEGIN_EXAM_DTTM < '2016-05-01'
AND CLARITY_LOC.loc_id in (13103,13108,13110,13109,13106)
AND CLARITY_EAP.PROC_CAT_ID in ('10', '11', '12', '13', '14', '16', '17', '18', '20')
/*
10.IMG DIAGNOSTIC IMAGING ORDERABLES
11.IMG CT ORDERABLES
12.IMG MRI ORDERABLES
13.IMG NM ORDERABLES
14.IMG US ORDERABLES
16.IMG DEXA ORDERABLES
17.IMG MAMMOGRAPHY ORDERABLES
18.IMG IR ORDERABLES
20.IMG FLUOROSCOPY ORDERABLES
*/
order by 'Begin Exam Date'

--FTP: FTP:/epic/prdfiles/RadProFee/STR
