--CHANGELOG
--v1.0: Created (*bmarohn)
--v1.1: Removed duplicate columns for bill area and location (*jfreeze)
--v1.2: Fixed bad join causing many duplicate results (*bmarohn)
--
--USER INPUT
--JUST COMMENT WITH A -- EVERYTHING YOU DO NOT WANT TO REPORT ON
SELECT T1.CREATE_DATE
, SERVICE_DATE
, T1.DEPARTMENT_ID
--, DEPARTMENT_NAME
--, T1.LOCATION_ID
--, LOC_NAME
--, T1.POS_ID
--, POS_NAME
, T1.BILLING_PROVIDER_ID
, SER.PROV_NAME BILLING_PROVIDER_NAME
--, T1.SERVICE_PROVIDER_ID
--, SERSVC.PROV_NAME SERVICE_PROVIDER_NAME
--, T1.BILL_AREA_ID
--, BIL.RECORD_NAME BILL_AREA_NAME
--, T1.FIN_DIV_ID
--, FD.FIN_DIV_NM FINANCIAL_DIVISION_NAME
--, T1.FIN_SUBDIV_ID
--, FSD.FIN_SUBDIV_NM FINANCIAL_SUBDIVISION_NAME
--, BIL.RECORD_NAME 
 --, LOC.LOC_NAME LOCATION_NAME
, SUM(POSTED_AMOUNT) POSTED_AMOUNT
, SUM(CHGRVW_AMOUNT) CHGRVW_AMOUNT
, SUM(CHGRTR_AMOUNT) CHGRTR_AMOUNT
, T1.SERVICE_AREA_ID
-----------------------------
--BEGIN NO USER NEEDED CHANGE 
FROM (
SELECT TDL.POST_DATE CREATE_DATE
  , TDL.ORIG_SERVICE_DATE SERVICE_DATE
  , TDL.DEPT_ID DEPARTMENT_ID
  , TDL.LOC_ID LOCATION_ID
  , TDL.POS_ID
  , TDL.SERV_AREA_ID SERVICE_AREA_ID
  , TDL.BILLING_PROVIDER_ID
  , TDL.PERFORMING_PROV_ID SERVICE_PROVIDER_ID
  , TDL.BILL_AREA_ID
  , TDL.FIN_SUBDIV_ID
  , TDL.FIN_DIV_ID
  , AMOUNT POSTED_AMOUNT
  , 0 CHGRVW_AMOUNT
  , 0 CHGRTR_AMOUNT
FROM CLARITY_TDL_TRAN TDL
WHERE TDL.DETAIL_TYPE IN (1, 10)

 UNION ALL

 SELECT TARHX.ACTIVITY_DATE CREATE_DATE
  , TAR.SERVICE_DATE SERVICE_DATE
  , TAR.PROC_DEPT_ID DEPARTMENT_ID
  , TAR.LOC_ID LOCATION_ID
  , TAR.PROC_POS_ID POS_ID
  , TAR.SERV_AREA_ID SERVICE_AREA_ID
  , TAR.BILL_PROV_ID BILLING_PROVIDER_ID
  , TAR.PERF_PROV_ID SERVICE_PROVIDER_ID
  , TAR.BILL_AREA_ID
  , TAR.FIN_SUBDIV_ID FIN_SUBDIV_ID
  , TAR.FIN_DIV_ID FIN_DIV_ID  
  , 0 POSTED_AMOUNT
  , TAR.AMOUNT CHGRVW_AMOUNT
  , 0 CHGRTR_AMOUNT
FROM PRE_AR_CHG TAR
LEFT OUTER JOIN PRE_AR_CHG_HX TARHX ON TAR.TAR_ID = TARHX.TAR_ID
  AND TARHX.ACTIVITY_C = 101 --CHARGE SESSION CREATED
WHERE TAR.CHARGE_STATUS_C = 3 --IN REVIEW

UNION ALL

SELECT UCL.TRIGGERED_DATE CREATE_DATE
  , UCL.SERVICE_DATE_DT SERVICE_DATE
  , UCL.DEPARTMENT_ID
  , UCL.REVENUE_LOCATION_ID LOCATION_ID
  , UCL.PLACE_OF_SERVICE_ID
  , UCL.SERVICE_AREA_ID
  , UCL.BILLING_PROVIDER_ID
  , UCL.SERVICE_PROVIDER_ID
  , UCL.PROV_BILL_AREA_C BILL_AREA_ID
  , FSD.FIN_SUBDIV_ID FIN_SUBDIV_ID
  , FD.FIN_DIV_ID FIN_DIV_ID
  , 0 POSTED_AMOUNT
  , 0 CHGRVW_AMOUNT
  , UCL2.EXPECTED_PRICE CHGRTR_AMOUNT
FROM CLARITY_UCL UCL
LEFT OUTER JOIN CLARITY_UCL_2 UCL2 ON UCL.UCL_ID = UCL2.UCL_ID 
 INNER JOIN UCS_WQ_HISTORY UCS ON UCS.SESSION_ID = UCL.CHARGE_SESSION_ID AND UCS.LINE = 1   --SEE THAT IT WENT INTO A WQ AT ONE TIME SO NOT IN POSTING STILL
LEFT OUTER JOIN BILL_AREA BIL ON UCL.PROV_BILL_AREA_C = BIL.BILL_AREA_ID
LEFT OUTER JOIN FIN_SUBDIV FSD ON BIL.FIN_SUBDIV_ID = FSD.FIN_SUBDIV_ID
LEFT OUTER JOIN FIN_DIV FD ON BIL.FIN_DIV_ID = FD.FIN_DIV_ID
WHERE UCL2.EXPECTED_DEST_C = 8
  AND UCL.CHARGE_FILED_TIME IS NULL   --THIS AND THE NEXT CHECK ARE CLOSELY SIMILAR TO WHAT THE ZRZL DOES, WE CHECK WQS ABOVE WITH THE UCS JOIN
  AND UCL.SYSTEM_FLAG_C IN (1,3)
) T1
LEFT OUTER JOIN CLARITY_SER SER ON T1.BILLING_PROVIDER_ID = SER.PROV_ID
LEFT OUTER JOIN CLARITY_SER SERSVC ON T1.SERVICE_PROVIDER_ID = SERSVC.PROV_ID
LEFT OUTER JOIN BILL_AREA BIL ON T1.BILL_AREA_ID = BIL.BILL_AREA_ID
LEFT OUTER JOIN FIN_SUBDIV FSD ON T1.FIN_SUBDIV_ID = FSD.FIN_SUBDIV_ID
LEFT OUTER JOIN FIN_DIV FD ON T1.FIN_DIV_ID = FD.FIN_DIV_ID
LEFT OUTER JOIN CLARITY_DEP DEP ON T1.DEPARTMENT_ID = DEP.DEPARTMENT_ID
LEFT OUTER JOIN CLARITY_LOC LOC ON T1.LOCATION_ID = LOC.LOC_ID
LEFT OUTER JOIN CLARITY_POS POS ON T1.POS_ID = POS.POS_ID
--END NO USER NEEDED CHANGE 
---------------------------
--USER INPUT
--CHANGE THIS TO APPROPRIATE SERVICE AREA
WHERE T1.SERVICE_AREA_ID = 1312    
  --AND CREATE_DATE >= '2015-06-22'   --CHANGE THIS TO YOUR GO-LIVE DATE IN YYYY-MM-DD FORMAT
--JUST COMMENT WITH A -- EVERYTHING YOU DO NOT WANT TO REPORT ON
GROUP BY CREATE_DATE
, SERVICE_DATE
, T1.DEPARTMENT_ID
, DEPARTMENT_NAME
--, T1.LOCATION_ID
--, LOC_NAME
--, T1.POS_ID
--, POS_NAME
, T1.BILLING_PROVIDER_ID
, SER.PROV_NAME
--, T1.SERVICE_PROVIDER_ID
--, SERSVC.PROV_NAME
--, T1.BILL_AREA_ID
--, BIL.RECORD_NAME
--, T1.FIN_SUBDIV_ID
--, FSD.FIN_SUBDIV_NM
--, T1.FIN_DIV_ID
--, FD.FIN_DIV_NM
, T1.SERVICE_AREA_ID
