SELECT

DISTINCT
TAX_ID -- INV 55
,INV.SERV_AREA_ID -- INV 51
,SERV_AREA_NAME
,INV.LOC_ID -- INV 52
,LOC_NAME
,INV.PROV_ID -- INV 31
,PROV_NAME 
,PROV_TYPE


FROM INVOICE INV
LEFT JOIN INV_BASIC_INFO IBI ON IBI.INV_ID = INV.INVOICE_ID
LEFT JOIN CLARITY_SER SER ON SER.PROV_ID = INV.PROV_ID
LEFT JOIN CLARITY_SA SA ON SA.SERV_AREA_ID = INV.SERV_AREA_ID
LEFT JOIN CLARITY_LOC LOC ON LOC.LOC_ID = INV.LOC_ID

WHERE

FROM_SVC_DATE >= '09/01/2016' -- INV 106
AND INV.SERV_AREA_ID IN (11,13,16,17,18,19)

ORDER BY TAX_ID